### ISSUE TITLE
TypeError: simpledownload is not a function

### ISSUE THREAD

**Issue by vsnthdev** [alsotang/simpledownload#1]
### 🐛 What happens

We get 👇 if we default import `simpledownload` as per the documentation.

![error](https://user-images.githubusercontent.com/24322511/158242805-c6fcfcb4-6409-47d8-a073-f2a91cb9056a.jpg)

### ✅ What should happen

We should not get an error saying `TypeError: simpledownload is not a function` and the file should successfully download 👇

![ideal output](https://user-images.githubusercontent.com/24322511/158241542-e9590341-8283-4524-9e39-6b6aba40a5a7.jpg)

### ↪️ Steps to reproduce

1. Create a new directory & `cd` into it
2. Create a new `package.json` by running `npm init -y`
3. Set `"type": "module"` in `package.json` to enable native ESM modules
4. Run `npm i simpledownload` to install `simpledownload` from npmjs
6. Create a new file named `app.js` & add the following code 👇

```js
import simpledownload from 'simpledownload'

await simpledownload('https://cdn2.thecatapi.com/images/MTg3NTQ4NA.jpg', 'cat.jpg')
```

7. Run it with `node app.js` to get the error.

### ℹ️ Information

1. **Node.js:** v17.7.1
2. **npm:** v8.5.2
3. **Operating System:** Windows 11 (Version 21H2 Build 22000.556)

**Comment by vsnthdev** [comment]
### 🛠️ Temporary Workaround

Use a destructured import instead 👇

```js
import { simpledownload } from 'simpledownload'

await simpledownload('https://cdn2.thecatapi.com/images/MTg3NTQ4NA.jpg', 'cat.jpg')
```

**Comment by alsotang** [comment]
I tried it and found that the compile result of typescript is not full fit to native es6 module type. Especially when working with `default` export.

`default` export is always a problem. I met it before when upgrade babel5 to babel6. So I just delete the default export to solve this issue.  https://github.com/alsotang/simpledownload/commit/5afe546e0ca613fc86e8922a540706e337c87c19

**Comment by vsnthdev** [comment]
Alright, that solves it ✅

Thank you!

**Comment by alsotang** [comment]
thank you
